// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:35b252b7-f13b-4803-b34c-ccf7c3dad3b1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_G8CzYMvoA",
    "aws_user_pools_web_client_id": "4g8hkge07fovksk4ta6kj4ksvf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ejrv5vpdbraqrmozadxwb2ipo4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sm7gt64mxvfr3pagc7us36xsdq",
    "aws_content_delivery_bucket": "viq-recording-portal-hosting-staging",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://viq-recording-portal-hosting-staging.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
