// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:4b50f332-fb2a-4e1f-adbc-9e9edef24468",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_6pvsFZW4O",
    "aws_user_pools_web_client_id": "lvdsepv523q70p1kttfdst7fs",
    "oauth": {},
    "aws_content_delivery_bucket": "viq-recording-portal-hosting-austaging",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://viq-recording-portal-hosting-austaging.s3-website-ap-southeast-2.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://rbyeigowefeotmfcr54ofbfx24.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h4xhlesslndwddajuwsz3byyry"
};


export default awsmobile;
