// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:365bb8df-2beb-48db-bd35-6e8b68d980cc",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_udoJHQaIT",
    "aws_user_pools_web_client_id": "3ldpcrqmhbsmffarvmq18997v3",
    "oauth": {},
    "aws_content_delivery_bucket": "viq-recording-portal-hosting-testuk",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://viq-recording-portal-hosting-testuk.s3-website.eu-west-2.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://6fdyfehzj5dyxh7gvs2ammvz3i.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v7xaqqmghrdwjkg7zghunznadi"
};


export default awsmobile;
