// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e99b904-e404-4811-8458-bf1d9982a7d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_j3pUW2SRD",
    "aws_user_pools_web_client_id": "4ak2462rmcojp4ill93hulvpov",
    "oauth": {},
    "aws_content_delivery_bucket": "viq-recording-portal-hosting-testnew",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://viq-recording-portal-hosting-testnew.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://ktwh6srkivcubipewfzewjxjq4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-opf6l3yilndyric5pm2rydl2e4"
};


export default awsmobile;

