// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ceffae04-07cb-4b07-a443-f0d2d2b052ed",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_308Aytf7T",
    "aws_user_pools_web_client_id": "3cih6joe79j4ana0h08l16sn9o",
    "oauth": {},
    "aws_content_delivery_bucket": "viq-recording-portal-hosting-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://viq-recording-portal-hosting-dev.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://mjwo2ptclzdpfd5voj4ven5zym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cb6z7qmq6vferoxanfirsaqaom"
};


export default awsmobile;

