// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9d42250f-c517-40f4-b96b-3faa893a4891",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RFM5v4sKU",
    "aws_user_pools_web_client_id": "53agafp06970cbgai7hof9jq5j",
    "oauth": {},
    "aws_content_delivery_bucket": "viq-recoding-portal-hosting-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://viq-recoding-portal-hosting-dev.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://bqv6twt4mveldoahuxqaxuigum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mof3dj2w3vdkzjpgclw5ppuq7i"
};
export default awsmobile;

